Change crypto setting in UI
Charge-Angels/ev-dashboard pull request #2215
Opened 2021-01-20 11:03 UTC by stefania-santimbrean

2021-01-20 11:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/LucasBrazi06/ev-dashboard?pullRequest=2215) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/LucasBrazi06/ev-dashboard?pullRequest=2215) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/LucasBrazi06/ev-dashboard?pullRequest=2215) it.</sub>

2021-02-04 09:16 UTC, LucasBrazi06 requested changes

2021-02-04 09:16 UTC, LucasBrazi06 commented on src/app/pages/settings-technical/crypto/settings-crypto.component.ts
> +    if (this.cryptoSettings.crypto.migrationToBeDone) {
No, the request has to be sent to the backend and the backend will return an HTTP error code and you will display the right error message.
Check HTTPError type.

2021-02-04 09:16 UTC, LucasBrazi06 commented on src/assets/i18n/en.json
> +      "migration_in_progress_warning": "Crypto Settings cannot be changed while migration is in progress."
Have you changed also all other i18n !?
Golden rule #4

2021-02-07 21:21 UTC, LucasBrazi06 approved these changes

2021-02-26 21:55 UTC, LucasBrazi06 commented
@jerome-benoit It seems that the UI does not fully enforce values below!!! I entered a long key and made the migration failed and blocked!!!

I need your advice here.
Should we make the block size/cypher/operation mode read-only?
Also the key may also change according the fields below.
Let me know so I'll add the missing assertions in the UI and backend.
Thanks in advance!

![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/294c643e-d62b-46c5-a6e9-4db4cd4660ef)

2021-02-27 22:36 UTC, LucasBrazi06 reviewed
I would need more check on UI element like check of the key length, algorithm...

2021-02-27 23:00 UTC, merged

2021-02-28 09:01 UTC, jerome-benoit commented
> @jerome-benoit <https://github.com/jerome-benoit> It seems that the UI does not fully enforce values below!!! I entered a long key and made the migration failed and blocked!!!
> 
> I need your advice here.
> Should we make the block size/cypher/operation mode read-only?
> Also the key may also change according the fields below.
> Let me know so I'll add the missing assertions in the UI and backend.
> Thanks in advance!
> 

It should have been dropdown manus depending on the symmetric cypher algo.
The secure settings are aes 256 gcm and it’s currently the default. They can stay read only as long as at key change, the default are shown instead of the current ones.

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

2021-02-28 14:11 UTC, LucasBrazi06 commented
> It should have been dropdown manus depending on the symmetric cypher algo. The secure settings are aes 256 gcm and it’s currently the default. They can stay read only as long as at key change, the default are shown instead of the current ones.

Ok, let the user changes only the key then for the time being.
We can propose later on a limited list of algo that we allow in a new drop-down.
Btw, default is aes-256-ctr (not aes-256-gcm):

![image](https://user-images.githubusercontent.com/25266945/109421259-db0da980-79d6-11eb-99bc-dec717a47f93.png)

2021-02-28 14:13 UTC, LucasBrazi06 commented
@jerome-benoit also you can limit the list of supported algos in Constants class:

![image](https://user-images.githubusercontent.com/25266945/109421392-6d15b200-79d7-11eb-884e-402c1d622d69.png)

2021-02-28 18:04 UTC, jerome-benoit commented
> Btw, default is aes-256-ctr (not aes-256-gcm):
> 
>  <https://user-images.githubusercontent.com/25266945/109421259-db0da980-79d6-11eb-99bc-dec717a47f93.png>
> 

That’s not the secure default I’ve request during the development, it shall be aes-256-gcm.

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

2021-03-01 08:14 UTC, LucasBrazi06 commented
> That’s not the secure default I’ve request during the development, it shall be aes-256-gcm.

She had done gcm but this was not working with current configuration, not tested in new tenant.
So I think we need another migration task for this one.