Implement update of registration token
Charge-Angels/ev-dashboard pull request #2227
Opened 2021-02-01 14:58 UTC by cabch

2021-02-02 12:35 UTC, ClaudeROSSI approved these changes

2021-02-02 12:35 UTC, ClaudeROSSI commented on src/assets/i18n/en.json
> +      "registration_token_update_confirm": "Do you really want to update the registration token ?",
Contrairement au francais, il n'y a pas d'espace à gauche d'un point d'interrogation en anglais!
... the registration token?

2021-02-03 19:59 UTC, LucasBrazi06 requested changes
Small request

2021-02-05 20:19 UTC, LucasBrazi06 requested changes
Gut!
Last step is to align all the button actions with the rest of the UI by creating a table action class in the below directory and use it in the controller.
It's just encapsulating the code of the action in the class like table-create-charging-station-token-action.ts
Check this directory, class table-edit-, table-delete-,:
![image](https://user-images.githubusercontent.com/25266945/107084433-5674a480-67f7-11eb-9252-6e83f793ffe2.png)

2021-02-22 18:32 UTC, merged